- hosts: localhost
  vars_files:
    - group_vars/vault/secrets
  roles:
    - role: srsp.oracle-java
      vars:
        java_set_javahome: true
    - role: robdyke.maven
    - role: mysql
    - role: jdauphant.ssl-certs
      vars:
        ssl_certs_common_name: "hotelspring.com"
        ssl_certs_path_owner: "root"
        ssl_certs_path_group: "root"
        ssl_certs_country: "CZ"
        ssl_certs_locality: "Prague"
        ssl_certs_organization: "Hotel Spring"
        ssl_certs_state: "Prague"
    - role: nginx
      vars:
        domain_name: "hotelspring.com"
        http_to_https_redirection: yes
        use_ssl: yes
        ssl_on: yes
        ssl_certificate_path: "/etc/ssl/hotelspring.com/hotelspring.com.pem"
        ssl_certificate_key_path: "/etc/ssl/hotelspring.com/hotelspring.com.key"
        proxy_on: yes
        proxy_pass_server: "localhost"
        proxy_pass_port: "8091"
    - role: appdeploy
      vars:
        app_user: "hotelspring"
        app_group: "hotelspring"
        app_path: "/opt/{{ app_name }}"
        app_description: "Sample app"
        app_extention: ".jar"
        app_name: "hotelspring"
                
