---
# Maven major version number
maven_version_major: '3'
# Maven minor version number
maven_version_minor: '5'
# Maven patch version number
maven_version_patch: '2'

# Mirror where to dowload Maven redistributable package from
maven_mirror: "http://mirror.ox.ac.uk/sites/rsync.apache.org/maven"

# SHA256 sum for the Maven redistributable package
maven_redis_sha256sum: '707b1f6e390a65bde4af4cdaf2a24d45fc19a6ded00fff02e91626e3e42ceaff'

# mvn binary gets symlinked into {{ maven_bin_path }}
maven_bin_path: '/usr/local/bin'

# Version of our role.
maven_role_version: '0.1.1'

# path for ansible to store downloaded or templated data
ansible_data_path: '/usr/local/src/ansible/data'

# base installation directory for any Maven distribution
maven_install_dir: '/opt/maven'

# concatenated Maven version
maven_version: "{{ maven_version_major }}.{{ maven_version_minor }}.{{ maven_version_patch }}"

# filename of Maven redistributable package
maven_redis_filename: "apache-maven-{{ maven_version }}-bin.tar.gz"
